Encoding:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

DoubleNegation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - "bin/**/*"
    - "Guardfile"
